
# Jaeger ConfigMap for UI
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ui-configmap
  namespace: jaegerspm
data:
  jaeger-ui.json: |-
    {
      "monitor": {
        "menuEnabled": true
      },
      "dependencies": {
        "menuEnabled": true
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
  namespace: jaegerspm
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - args:
            - --query.ui-config
            - /etc/jaeger/ui/jaeger-ui.json
          env:
            - name: METRICS_BACKEND
              value: "prometheus"
            - name: METRICS_STORAGE_TYPE
              value: "prometheus"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: PROMETHEUS_QUERY_NORMALIZE_CALLS
              value: "true"
            - name: PROMETHEUS_QUERY_NORMALIZE_DURATION
              value: "true"
            - name: PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR
              value: "true"
            - name: PROMETHEUS_SERVER_URL
              value: "http://prometheus-service.jaegerspm.svc.cluster.local:9090/"
          image: jaegertracing/all-in-one:1.52
          imagePullPolicy: IfNotPresent
          name: jaeger
          ports:
            - containerPort: 16686
          volumeMounts:
            - mountPath: /etc/jaeger/ui
              name: jaeger-volume
      restartPolicy: Always
      volumes:
        - name: jaeger-volume
          configMap:
              name: jaeger-ui-configmap
              items:
                - key: jaeger-ui.json
                  path: jaeger-ui.json
---
# Jaeger Service
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: jaegerspm
spec:
  selector:
    app: jaeger
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686

