apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-configmap
  namespace: jaegerspm
data:
  otel-collector-config.yml: |-
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      jaeger:
        protocols:
          thrift_http:
            endpoint: "0.0.0.0:14278" 
     
      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: "localhost:65535"


    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      otlp:
        endpoint: "10.224.0.108:4317"
        tls:
          insecure: true

    

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          exporters: [otlp]
        metrics: 
          receivers: [otlp/spanmetrics] # Reference the spanmetrics receiver here
          exporters: [prometheus]

        
---
# Otel-Collector Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-deployment
  namespace: jaegerspm
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - args:
            - --config
            - /etc/otelcol/otel-collector-config.yml
          image: otel/opentelemetry-collector-contrib:0.91.0
          imagePullPolicy: IfNotPresent
          name: otel-collector
          ports:
            - containerPort: 14278
            - containerPort: 8889
            - containerPort: 4317
          volumeMounts:
            - mountPath: /etc/otelcol
              name: otel-collector-volume
      restartPolicy: Always
      volumes:
        - name: otel-collector-volume
          configMap:
              name: otel-collector-configmap
              items:
                - key: otel-collector-config.yml
                  path: otel-collector-config.yml
---
# Otel-Collector Service
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: jaegerspm
spec:
  selector:
    app: otel-collector
  ports:
    - name: "14278"
      port: 14278
      targetPort: 14278
    - name: "8889"
      port: 8889
      targetPort: 8889
    - name: "4317"
      port: 4317
      targetPort: 4317
    
