collector:
  prometheus:
    enabled: true
    config:
      scrape_configs:
        - job_name: 'jaeger'
          scrape_interval: 10s
          static_configs:
            - targets: ['jaeger:14269']
